#!/bin/bash
#
# Wile Container Entrypoint
# Clones repo, sets up workspace, runs the autonomous coding loop
#

set -e

echo "══════════════════════════════════════════════════════"
echo "  🌵  WILE - Container Startup"
echo "══════════════════════════════════════════════════════"

if command -v sysctl >/dev/null 2>&1; then
  sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1 || true
  sysctl -w net.ipv6.conf.default.disable_ipv6=0 >/dev/null 2>&1 || true
fi

if [ "${WILE_TEST:-}" = "true" ]; then
  TEST_REPO="${WILE_TEST_REPO_PATH:-/home/wile/workspace/repo}"

  if [ ! -d "$TEST_REPO" ]; then
    echo "ERROR: WILE_TEST_REPO_PATH does not exist: $TEST_REPO"
    exit 1
  fi

  cd "$TEST_REPO"

  if [ ! -f ".wile/prd.json" ]; then
    echo "ERROR: .wile/prd.json not found in test repo"
    exit 1
  fi

  echo "TEST MODE: running mocked agent (no GitHub, no Claude)"

  node - << 'NODE'
const fs = require('fs');
const path = require('path');

const prdPath = path.join('.wile', 'prd.json');
const progressPath = path.join('.wile', 'progress.txt');

const prd = JSON.parse(fs.readFileSync(prdPath, 'utf8'));
const stories = Array.isArray(prd.userStories) ? prd.userStories : [];
const pending = stories.filter((story) => story.passes === false);

if (process.env.TEST_FORWARD) {
  console.log(`Forwarded env: ${process.env.TEST_FORWARD}`);
}

if (pending.length === 0) {
  console.log('No pending stories to complete in test mode.');
  process.exit(0);
}

pending.sort((a, b) => {
  const aPriority = typeof a.priority === 'number' ? a.priority : Number.MAX_SAFE_INTEGER;
  const bPriority = typeof b.priority === 'number' ? b.priority : Number.MAX_SAFE_INTEGER;
  return aPriority - bPriority;
});

const story = pending[0];
story.passes = true;
fs.writeFileSync(prdPath, JSON.stringify(prd, null, 2) + '\n');

if (!fs.existsSync(progressPath)) {
  fs.writeFileSync(progressPath, '# Wile Progress Log\n\n## Codebase Patterns\n(Autogenerated in test mode)\n\n---\n');
}

const date = new Date().toISOString().split('T')[0];
const entry = `\n---\n\n## ${date} - ${story.id}: ${story.title}\n\n**Implemented:**\n- Mocked test mode completion\n\n**Files changed:**\n- .wile/prd.json\n- .wile/progress.txt\n\n**Learnings:**\n- Test mode mock run\n`;

fs.appendFileSync(progressPath, entry);
console.log(`Marked ${story.id} complete (test mode).`);
NODE

  exit 0
fi

CODING_AGENT="${CODING_AGENT:-CC}"
REPO_SOURCE="${WILE_REPO_SOURCE:-github}"
LOCAL_REPO_PATH="${WILE_LOCAL_REPO_PATH:-/home/wile/workspace/repo}"
ADDITIONAL_INSTRUCTIONS_PATH="${WILE_ADDITIONAL_INSTRUCTIONS:-}"

echo "  Agent:      $CODING_AGENT"
if [ "$REPO_SOURCE" = "local" ]; then
  if [ ! -d "$LOCAL_REPO_PATH" ]; then
    echo "ERROR: WILE_LOCAL_REPO_PATH does not exist: $LOCAL_REPO_PATH"
    exit 1
  fi
else
  # Required environment variables
  : "${GITHUB_REPO_URL:?GITHUB_REPO_URL is required}"
  : "${BRANCH_NAME:?BRANCH_NAME is required}"
  : "${GITHUB_TOKEN:?GITHUB_TOKEN is required}"
fi

# Authentication for selected coding agent
if [ "$CODING_AGENT" = "OC" ]; then
  OC_PROVIDER="${OC_PROVIDER:-native}"
  if [ "$OC_PROVIDER" = "openrouter" ] && [ -z "$OC_OPENROUTER_API_KEY" ]; then
    echo "ERROR: OC_OPENROUTER_API_KEY is required for OpenCode with OpenRouter provider"
    exit 1
  fi
  if [ -z "$OC_MODEL" ]; then
    echo "ERROR: OC_MODEL is required for OpenCode"
    exit 1
  fi
else
  if [ -z "$CC_CLAUDE_CODE_OAUTH_TOKEN" ] && [ -z "$CC_ANTHROPIC_API_KEY" ]; then
    echo "ERROR: Either CC_CLAUDE_CODE_OAUTH_TOKEN or CC_ANTHROPIC_API_KEY is required"
    echo ""
    echo "  CC_CLAUDE_CODE_OAUTH_TOKEN - Uses your Pro/Max subscription (recommended)"
    echo "  CC_ANTHROPIC_API_KEY       - Uses API credits (pay per token)"
    echo ""
    echo "Run 'claude setup-token' on your local machine to get an OAuth token."
    exit 1
  fi
fi

MAX_ITERATIONS=${MAX_ITERATIONS:-25}
SCRIPT_DIR="/home/wile/scripts"
WORKSPACE="/home/wile/workspace"

if [ "${WILE_MOCK_CLAUDE:-}" = "true" ] && [ "$CODING_AGENT" = "CC" ]; then
  echo "  Claude:     Mocked"
  MOCK_BIN="/home/wile/mock-bin"
  mkdir -p "$MOCK_BIN"
  cp "$SCRIPT_DIR/mock-claude.sh" "$MOCK_BIN/claude"
  chmod +x "$MOCK_BIN/claude"
  export PATH="$MOCK_BIN:$PATH"
fi

if [ "$CODING_AGENT" = "OC" ]; then
  if [ "$OC_PROVIDER" = "openrouter" ]; then
    echo "  Auth:       OpenRouter (OpenCode)"
    OPENCODE_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/opencode"
    mkdir -p "$OPENCODE_DATA_DIR"
    cat > "$OPENCODE_DATA_DIR/auth.json" << OPENCODEAUTH
{
  "openrouter": {
    "type": "api",
    "key": "$OC_OPENROUTER_API_KEY"
  }
}
OPENCODEAUTH
    chmod 600 "$OPENCODE_DATA_DIR/auth.json"
    export OPENROUTER_API_KEY="$OC_OPENROUTER_API_KEY"
  else
    echo "  Auth:       Native (free models)"
  fi
else
  # Set up Claude Code authentication
  if [ -n "$CC_CLAUDE_CODE_OAUTH_TOKEN" ]; then
    echo "  Auth:       OAuth (Pro/Max subscription)"

    # Create required directories
    mkdir -p ~/.claude ~/.config/claude

    # Create ~/.claude.json (THE CRITICAL FILE!)
    # Without this, Claude Code thinks it's a fresh install and breaks
    cat > ~/.claude.json << 'CLAUDEJSON'
{
  "hasCompletedOnboarding": true,
  "theme": "dark"
}
CLAUDEJSON

    # Create credentials file with the OAuth token
    cat > ~/.claude/.credentials.json << CREDSJSON
{
  "claudeAiOauth": {
    "accessToken": "$CC_CLAUDE_CODE_OAUTH_TOKEN",
    "refreshToken": "$CC_CLAUDE_CODE_OAUTH_TOKEN",
    "expiresAt": 9999999999999,
    "scopes": ["user:inference", "user:profile"]
  }
}
CREDSJSON

    # Copy to alternate location too
    cp ~/.claude/.credentials.json ~/.config/claude/.credentials.json

    # Ensure ANTHROPIC_API_KEY is not set (it overrides OAuth)
    unset ANTHROPIC_API_KEY
  else
    echo "  Auth:       API Key (credits)"
    export ANTHROPIC_API_KEY="$CC_ANTHROPIC_API_KEY"
  fi
fi

if [ "$REPO_SOURCE" = "local" ]; then
  echo "  Repo:       local ($LOCAL_REPO_PATH)"
else
  echo "  Repo:       $GITHUB_REPO_URL"
  echo "  Branch:     $BRANCH_NAME"
fi
echo "  Iterations: $MAX_ITERATIONS"
echo "══════════════════════════════════════════════════════"
echo ""

# Configure git
echo "Configuring git..."
git config --global user.name "wile"
git config --global user.email "wile@bot.local"
git config --global credential.helper store

if [ "$REPO_SOURCE" = "local" ]; then
  echo "Using local repo mount..."
  cd "$LOCAL_REPO_PATH"
else
  # Set up GitHub token authentication
  # Extract host from URL (handles both https://github.com/... and git@github.com:...)
  if [[ "$GITHUB_REPO_URL" =~ ^https://([^/]+)/ ]]; then
    GIT_HOST="${BASH_REMATCH[1]}"
    # Store credentials for HTTPS
    echo "https://x-access-token:${GITHUB_TOKEN}@${GIT_HOST}" > ~/.git-credentials
  elif [[ "$GITHUB_REPO_URL" =~ ^git@([^:]+): ]]; then
    GIT_HOST="${BASH_REMATCH[1]}"
    # Convert to HTTPS for token auth
    GITHUB_REPO_URL=$(echo "$GITHUB_REPO_URL" | sed 's|git@\([^:]*\):|https://\1/|')
    echo "https://x-access-token:${GITHUB_TOKEN}@${GIT_HOST}" > ~/.git-credentials
  fi

  # Clone the repository
  echo "Cloning repository..."
  cd "$WORKSPACE"
  git clone "$GITHUB_REPO_URL" repo
  cd repo

  # Checkout the branch
  echo "Checking out branch: $BRANCH_NAME"
  git fetch origin
  if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH_NAME"; then
    git checkout "$BRANCH_NAME"
  else
    echo "Branch $BRANCH_NAME does not exist remotely. Creating it..."
    git checkout -b "$BRANCH_NAME"
    git push -u origin "$BRANCH_NAME"
  fi
fi

if [ -n "$ADDITIONAL_INSTRUCTIONS_PATH" ] && [ -f "$ADDITIONAL_INSTRUCTIONS_PATH" ]; then
  if [ -s "$ADDITIONAL_INSTRUCTIONS_PATH" ]; then
    echo "  Extra:      Using additional instructions"
  fi
fi

# Verify .wile/prd.json exists
echo "Checking for .wile/prd.json..."
if [ ! -f ".wile/prd.json" ]; then
  echo "ERROR: .wile/prd.json not found!"
  echo ""
  echo "Your repository must have a .wile/prd.json file at the root."
  echo "This file contains the user stories for Wile to implement."
  echo ""
  echo "Example structure:"
  echo '  {'
  echo '    "userStories": ['
  echo '      {'
  echo '        "id": "US-001",'
  echo '        "title": "My feature",'
  echo '        "acceptanceCriteria": ["..."],'
  echo '        "priority": 1,'
  echo '        "passes": false'
  echo '      }'
  echo '    ]'
  echo '  }'
  exit 1
fi

# Set up .wile/screenshots directory
echo "Setting up .wile directory..."
mkdir -p .wile/screenshots

echo ""
echo "══════════════════════════════════════════════════════"
if [ "${WILE_MODE:-}" = "compact" ]; then
  echo "  Starting Wile Compact"
else
  echo "  Starting Wile Loop"
fi
echo "══════════════════════════════════════════════════════"
echo ""

# Run the main loop or compact flow
EXIT_CODE=0
if [ "${WILE_MODE:-}" = "compact" ]; then
  "$SCRIPT_DIR/wile-compact.sh" || EXIT_CODE=$?
else
  "$SCRIPT_DIR/wile.sh" "$MAX_ITERATIONS" || EXIT_CODE=$?
fi

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Wile Loop Complete (exit code: $EXIT_CODE)"
echo "══════════════════════════════════════════════════════"

# Handle completion/partial completion
if [ $EXIT_CODE -eq 0 ]; then
  echo "All tasks completed successfully!"
  if [ "${WILE_MODE:-}" = "compact" ]; then
    if ! git diff --quiet || ! git diff --staged --quiet; then
      git add -A
      git commit -m "chore: compact wile prd and progress"
      git push || true
    else
      git push || true
    fi
  else
    # Ensure final state is pushed
    git push || true
  fi
elif [ $EXIT_CODE -eq 1 ]; then
  echo "Max iterations reached. Committing partial work..."

  # Check if there are uncommitted changes
  if ! git diff --quiet || ! git diff --staged --quiet; then
    git add -A
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    git commit -m "WIP: wile stopped at max iterations ($TIMESTAMP)

Partial work committed. Check .wile/progress.txt for details.
Some stories may still have passes=false in .wile/prd.json."
    git push
  fi
elif [ $EXIT_CODE -eq 2 ]; then
  echo "Setup failed. Check the logs above for details."
else
  echo "Wile exited with error code: $EXIT_CODE"
  # Try to commit whatever state we have
  if ! git diff --quiet || ! git diff --staged --quiet; then
    git add -A
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    git commit -m "WIP: wile error exit ($TIMESTAMP)

Exit code: $EXIT_CODE
Check logs for details."
    git push || true
  fi
fi

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Wile Container Finished"
echo "══════════════════════════════════════════════════════"

exit $EXIT_CODE
